2021-04-04
Update inst

Cleaned things up a bit and removed of some testing/experimental stuff.
Set up network to use systemd-networkd and systemd-resolved rather than dhcpcd.
Setup custom systemd 'display.service' for 1730X970 resolution console.

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -1,43 +1,39 @@
 #!/bin/bash
-# inst-2018-11-23
-#
-# Arch install script
+# install script 2021-04-01
+# shellcheck disable=SC2002,SC2016,SC2129
+# SC2002: Useless cat
+# SC2016: Expressions don't expand in single quotes
+# SC2129: Consider not using cat > redirect
 
-# shellcheck disable=SC2002,SC2016
+####  FOR TESTING BACK TO BACK, QUICK SET UP A LOCAL PACMAN PACKAGE CACHE SERVER:
 ####  ---------------------------------------------------------------------------------------------------------------------------------------
-####  SET UP A LOCAL PACMAN CACHE:
-####  Symlink (-s) directory :  /var/cache/pacman/pkg/   to   /home/$USER/www/repo/
-####  Symlink contents of :     /var/cache/pacman/aur   and   /var/lib/pacman/sync/   to   /home/$USER/www/repo/
-####  ---------------------------------------------------------------------------------------------------------------------------------------
-####  sudo pacman -Sw --cachedir /home/$USER/www/repo/ --needed base base-devel <all other needed packages>
-####  sudo pacman -Syuw --cachedir /home/$USER/www/repo/
-####  Install darkhttpd (webfs won't do symlinks) and run: $ darkhttpd /home/$USER/www/repo --port 8080
-####  ---------------------------------------------------------------------------------------------------------------------------------------
-####  THIS INSTALL:
-####  sudo pacman -Sw --cachedir /home/$USER/www/repo/ --needed base base-devel grub wget sudo xorg-server xorg-xinit xterm xorg-fonts xorg-twm \
-####  virtualbox-guest-utils virtualbox-guest-modules-arch linux-headers polkit ttf-dejavu ttf-liberation leafpad xfce4 xfce4-goodies gvfs
+####  Install darkhttpd 
+####  Symlink package cache directory for darkhttpd :	$ sudo ln -s  /var/cache/pacman/pkg/    /home/$USER/www/repo/
+####  Setup darkhttpd run:				$ darkhttpd /home/$USER/www/repo --port 8080
+####  Configure package server IP variable 'LPSP' below
+####  sudo pacman -Sw --needed base base-devel + <all other desired packages> 
 ####  ---------------------------------------------------------------------------------------------------------------------------------------
 
-Fn1=0; Fn2=0; Fn3=0; Fn4=0; Fn5=0; Fn6=0; Fn7=0; Fn8=0; Fn9=0
 set -uo pipefail
 trap 'S="${?}" ; echo "${0}" : Error on line "${LINENO}" : "${BASH_COMMAND}" ; exit "${S}"' ERR
 
-### Save me from myself! Prevent running on my system in case 'chmod +x' gets set.
+	## Prevent accidentally running on my system!
 
-if 	[[ $(hostname) = Arch2014p9 ]]; then
+if 	[[ $HOSTNAME = Arch2014p9 ]]; then
 	echo " YOU REALLY DO NOT WANT TO RUN THIS "
 	exit
 fi
 
-#=====#=====# User, password, hostname, editor variables. #===========#
+#==========# User, password, hostname, editor, package server ip variables. #==========#
 
-URN="jeff"	## Username      ##
-URP="test"	## User Password ##
-RTP="test"	## Root Password ##
-HTN="Arch2018p12"	## Hostname      ##
-EDR="nano"	## Editor        ##
+URN="jeff"					## Username                  ##
+URP="test"					## User Password             ##
+RTP="test"					## Root Password             ##
+HTN="Arch2021p3"				## Hostname                  ##
+EDR="nano"					## Editor                    ##
+LPSP='Server = http://192.168.2.2:8080/'	## Local Package Server:Port ## Comment this out for none.
 
-#=====#=====# Partition variables. #===========#
+#==========# Partition variables. #==========#
 
 HDD="sda"		## set bootloader location. ##
 DDI="/dev/sda"		## set device for disklabel and installation. ##
@@ -46,9 +42,11 @@ ROOTP="/dev/sda1"	## set root partition. ##
 HOMEP="/dev/sda3"	## set home partition. ##
 SWAP="/dev/sda2"	## set swap partition. ##
 
-	umount "${HOMEP}"			|| /bin/true
-	umount "${ROOTP}"			|| /bin/true
+	umount "${HOMEP}" 2>/dev/null		|| /bin/true
+	umount "${ROOTP}" 2>/dev/null		|| /bin/true
 	swapoff "${SWAP}" 2>/dev/null		|| /bin/true
+
+#==========# SETUP PARTITIONS AND MOUNTS #==========#
 
 Partition(){
 
@@ -60,10 +58,11 @@ Partition(){
 }
 formats(){
 
-	yes | mkfs.ext4 "${ROOTP}"
-	yes | mkfs.ext4 "${HOMEP}"
+	mkfs.ext4 "${ROOTP}"
+	mkfs.ext4 "${HOMEP}"
 	mkswap /dev/sda2
 }
+
 mounts(){
 
 	mount  "${ROOTP}"	/mnt
@@ -72,77 +71,145 @@ mounts(){
 	swapon "${SWAP}"
 }
 
-#=====#=====# Local pacman cache/repo & mirrorlist #===========#
+#==========# SETUP INSTALL ISO FOR RUNNING INSTALL SCRIPT #==========#
 
 setrepos(){
 
-	pacman -Sy --noconfirm --needed reflector wgetpaste moreutils
-	echo 'Server = http://192.168.2.2:8080/' > /etc/pacman.d/mirrorlist
-	reflector --latest 5 --sort rate >> /etc/pacman.d/mirrorlist
-	echo; echo " /etc/pacman.d/mirrorlist in editor next" ; echo
+	pacman -Sy 2>/dev/null
+	pacman -S --noconfirm --needed reflector wgetpaste moreutils
+
+	echo "${LPSP}"										> /etc/pacman.d/mirrorlist
+	echo "Running reflector may take some time..."
+	reflector --latest 5 --country 'United States' --protocol https --sort rate 2>/dev/null >> /etc/pacman.d/mirrorlist
+	echo; echo " mirrorlist in editor next" ; echo
 	sleep 5
 
 	cat /etc/pacman.d/mirrorlist | EDITOR="${EDR}" vipe | awk '{print}' >tmp && mv tmp /etc/pacman.d/mirrorlist
 }
+
+#==========# INSTALL PACKAGES #==========#
+
 install(){
 
-	pacstrap /mnt   base base-devel grub wget sudo\
-			xorg-server xorg-xinit xterm xorg-fonts xorg-twm\
-			linux-headers polkit ttf-dejavu ttf-liberation leafpad\
-			xfce4 xfce4-goodies gvfs\
-			virtualbox-guest-utils virtualbox-guest-modules-arch\
+	## BASE VBOX INSTALL. EDIT LIST FOR INSTALLED PACKAGES ##
+
+	pacstrap /mnt   base linux linux-headers linux-firmware grub wget nano openssh sudo fbset terminus-font virtualbox-guest-utils
+
+		# dhcpcd
+		# xorg-server xorg-xinit xterm xorg-fonts xorg-twm \
+		# polkit ttf-dejavu ttf-liberation leafpad \
+		# virtualbox-guest-utils \
+		# xfce4 xfce4-goodies gvfs \
+		# xorg-server xorg-xinit xterm xorg-fonts xorg-twm \
+		# linux-headers polkit ttf-dejavu ttf-liberation leafpad \
+		# virtualbox-guest-utils \
+		# xfce4 xfce4-goodies gvfs
+}
+
+#==========# CONFIGURE SYSTEM #==========#
+
+Configure(){
 
 	genfstab -L /mnt > /mnt/etc/fstab
-}
-Configure(){
 
 	arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Los_Angeles		/etc/localtime
 	arch-chroot /mnt hwclock --systohc
 
-	echo "en_US.UTF-8 UTF-8" >>						/mnt/etc/locale.gen
+	echo "en_US.UTF-8 UTF-8" 						>> /mnt/etc/locale.gen
 	arch-chroot /mnt locale-gen
 
-	echo "LANG=en_US.UTF-8" >>						/mnt/etc/locale.conf
+	echo "LANG=en_US.UTF-8" 						>> /mnt/etc/locale.conf
 
-	echo "KEYMAP=us" >>							/mnt/etc/vconsole.conf
+	echo "KEYMAP=us"     							>> /mnt/etc/vconsole.conf
+	echo "FONT=ter-118n" 							>> /mnt/etc/vconsole.conf
 
-	echo "${HTN}" >								/mnt/etc/hostname
+	echo "${HTN}" 								> /mnt/etc/hostname
 
-	echo "127.0.1.1 ${HTN}.localdomain ${HTN}" >>				/mnt/etc/hosts
-	echo '# End of file' >>							/mnt/etc/hosts
+	echo '127.0.0.1  localhost'                 				>> /mnt/etc/hosts
+	echo '::1        localhost'                 				>> /mnt/etc/hosts
+	echo "127.0.1.1	 ${HTN}.localdomain ${HTN}" 				>> /mnt/etc/hosts
 
-	arch-chroot /mnt systemctl enable dhcpcd
+#	arch-chroot /mnt systemctl enable dhcpcd
 
 	arch-chroot /mnt grub-install --target=i386-pc /dev/"${HDD}"
 	arch-chroot /mnt grub-mkconfig -o 					/boot/grub/grub.cfg
 
-	arch-chroot /mnt useradd -m -g users -G wheel -s /bin/bash "${URN}"
+	arch-chroot /mnt useradd -m -G wheel -s /bin/bash "${URN}"
 
-	echo "${URN}:${URP}" | chpasswd -R /mnt
-	echo   "root:${RTP}" | chpasswd -R /mnt
+	### echo "root:${RTP}" | chpasswd -R /mnt ### BROKEN - replacement implemented 2021-03-30 ###
+
+	echo "${URN}:${URP}" | arch-chroot /mnt /usr/sbin/chpasswd	|| { echo "set password error" ; exit 1 ; }
+	echo   "root:${RTP}" | arch-chroot /mnt /usr/sbin/chpasswd	|| { echo "set password error" ; exit 2 ; }
 
 	arch-chroot /mnt systemctl enable systemd-timesyncd.service
 
 	sed -i '/%wheel ALL=(ALL) ALL/s/^#//'					/mnt/etc/sudoers
 
-	cp /mnt/etc/X11/xinit/xinitrc 						/mnt/home/$URN/.xinitrc
-	sed -i '/twm/s/^/#/g'         						/mnt/home/$URN/.xinitrc
-	sed -i '/xclock/s/^/#/g'      						/mnt/home/$URN/.xinitrc
-	sed -i '/xterm/s/^/#/g'       						/mnt/home/$URN/.xinitrc
-	echo 'exec startxfce4' >>     						/mnt/home/$URN/.xinitrc
-	arch-chroot /mnt chown $URN						    /home/$URN/.xinitrc
+	touch /mnt/etc/systemd/network/20-wired.network
 
-	cp /mnt/etc/X11/xinit/xserverrc						/mnt/home/$URN/.xserverrc
-	sed -i '/exec/s/^/#/g'							/mnt/home/$URN/.xserverrc
-	echo 'exec /usr/bin/Xorg -keeptty -nolisten tcp "$@" vt"$XDG_VTNR"' >>  /mnt/home/$URN/.xserverrc
-	arch-chroot /mnt chown $URN						    /home/$URN/.xserverrc
+	cat <<- EOF 								> /mnt/etc/systemd/network/20-wired.network
+	[Match]
+	Name=en*
+	Name=eth*
+
+	[Network]
+	DHCP=yes
+EOF
+	arch-chroot /mnt systemctl enable systemd-networkd
+	arch-chroot /mnt systemctl enable systemd-resolved
+
+
+	#### Added if statement to see if Xorg is installed and setup accordingle (WITH Xorg). ####
+
+if	[[ -e /mnt/etc/X11/xinit/xinitrc ]]; then
+
+	cp /mnt/etc/X11/xinit/xinitrc						/mnt/home/"${URN}"/.xinitrc
+	sed -i '/twm/s/^/#/g'							/mnt/home/"${URN}"/.xinitrc
+	sed -i '/xclock/s/^/#/g'      						/mnt/home/"${URN}"/.xinitrc
+	sed -i '/xterm/s/^/#/g'       						/mnt/home/"${URN}"/.xinitrc
+	echo 'exec startxfce4' >>     						/mnt/home/"${URN}"/.xinitrc
+	arch-chroot /mnt chown "${URN}"						/home/"${URN}"/.xinitrc
+
+	cp /mnt/etc/X11/xinit/xserverrc						/mnt/home/"${URN}"/.xserverrc
+	sed -i '/exec/s/^/#/g'							/mnt/home/"${URN}"/.xserverrc
+	echo 'exec /usr/bin/Xorg -keeptty -nolisten tcp "$@" vt"$XDG_VTNR"' >>  /mnt/home/"${URN}"/.xserverrc
+	arch-chroot /mnt chown "${URN}"						/home/"${URN}"/.xserverrc
+	arch-chroot /mnt systemctl enable vboxservice.service
+
+    else
+
+	#### (WITHOUT Xorg) Setup a service file to enlarge the vconsole resolution. ####
+
+	touch /mnt/etc/systemd/system/display.service
+
+	cat <<- EOF 								> /mnt/etc/systemd/system/display.service
+	[Unit]
+	Description=Display resolution
+	After=local-fs.target
+	DefaultDependencies=no
+
+	[Service]
+	Type=simple
+	ExecStart=/usr/bin/fbset -xres 1730 -yres 970
+
+	[Install]
+	WantedBy=multi-user.target
+
+EOF
+	arch-chroot /mnt systemctl enable display.service
+
+	echo ; echo "THIS IS A BASE, NO X INSTALL. KEEP THIS IN MIND FOR UPCOMING FILE CHECKS." ; echo
+	sleep 5
+fi
 }
+
 mesg(){
 
 	echo " The install is done except verifying and editing config files."
 	echo " Answering no here will exit, completing the install."
 	echo " Answering no after this will skip the named file/s."; echo
 }
+
 asksure(){
 		echo -n " Proceed ? (Y/N)"
 		while read -r -n 1 -s answer 
@@ -154,12 +221,15 @@ asksure(){
 		done
 	reset
 }
+
+#==========# CHECK CONFIG FILES WITH OPTION TO EDIT #==========#
+
 checking1(){
 		clear
 		echo; echo " Checking ~/.xinitrc in ${EDR}"
 		asksure
 	if	[[ $XX = 0 ]]; then
-		cat /mnt/home/$URN/.xinitrc | EDITOR="${EDR}" vipe | awk '{print}' >tmp && mv tmp /mnt/home/"${URN}"/.xinitrc
+		cat /mnt/home/"${URN}"/.xinitrc | EDITOR="${EDR}" vipe | awk '{print}' >tmp && mv tmp /mnt/home/"${URN}"/.xinitrc
 		reset
 			checking2
 		else
@@ -171,7 +241,7 @@ checking2(){
 		echo; echo " Checking ~/.xserverrc in ${EDR}"
 		asksure
 	if	[[ $XX = 0 ]]; then
-		cat /mnt/home/$URN/.xserverrc | EDITOR="${EDR}" vipe | awk '{print}' >tmp && mv tmp  /mnt/home/"${URN}"/.xserverrc
+		cat /mnt/home/"${URN}"/.xserverrc | EDITOR="${EDR}" vipe | awk '{print}' >tmp && mv tmp  /mnt/home/"${URN}"/.xserverrc
 		reset
 			checking3
 		else
@@ -225,73 +295,36 @@ checking6(){
 			XX=1
 	fi
 }
+
+#==========# UNMOUNT PARTITIONS  #==========#
+
 umnts(){
+
+	cp inst.log /mnt/home/"${URN}"/install.log
+
 	umount "${HOMEP}"
 	umount "${ROOTP}"
 	swapoff "${SWAP}"
 }
 
-### 'trap' below calls this function. WIP, Not passing vars.
-### Func file WORK AROUND for Not passing vars
+#==========# Run Functions #==========#
 
-cleanup(){
-
-if 	[[ $(<Func) != 9 ]]; then
-      # (( $Func < 9 )); then
-	umount "${HOMEP}"
-	umount "${ROOTP}"
-	swapoff "${SWAP}"  2>/dev/null
-	cat inst.log | tr -cd '\11\12\15\40-\176' > inst.log.bu
-	mv inst.log.bu inst.log
-	echo; tail -10 inst.log; echo
-	echo; echo "Something went wrong. ^ 10 last lines log ^. "
-	echo "  Func= $(<Func)"
-	pkill -9 inst
-	else
-	echo; echo " Successfully passed checks and completed cleanup. "; echo; exit
-fi
-}
-### Set trap for script crashes - exits 
-### Func file WORK AROUND for Not passing vars
-
-	trap 'cleanup' INT TERM EXIT
-
-###=====### Run Functions ###=====###
+## Group bracket below for logging ##
 {
-	Partition	; Fn1=1
-	formats		; Fn2=1
-	mounts		; Fn3=1 #; Fn1=1; Fn2=1
-	setrepos	; Fn4=1
-	install		; Fn5=1
-	Configure	; Fn6=1
-	mesg		; Fn7=1
-	asksure		; Fn8=1
+
+	Partition
+	formats
+	mounts
+	setrepos
+	install
+	Configure
+	mesg
+	asksure
 	if [[ $XX = 0 ]]; then checking1 ; fi
+	umnts
+	echo ; echo " Install log available, run 'less inst.log'"
+	echo " and has been copied to new install /home/${URN}"/install.log ; echo
 
-lurl=$(wgetpaste /root/inst.log 2>/dev/null )
-surl=$(wgetpaste -u "${lurl}" 2>/dev/null )
-
-	echo ; echo "Remote log long URL : ${lurl}" >> /mnt/home/"${URN}"/inst.log
-	echo "Remote log short URL: ${surl}" >> /mnt/home/"${URN}"/inst.log ; echo
-	echo "Remote log long URL : ${lurl}"
-	echo "Remote log short URL: ${surl}"
-	cat inst.log | tr -cd '\11\12\15\40-\176' > inst.log.bu
-	mv inst.log.bu inst.log
-	cp /root/inst.log /mnt/home/${URN}/inst.log
-	arch-chroot /mnt chown "${URN}" /home/"${URN}"/inst.log
-	echo; echo " Install Completed, running checks."; echo
-
-	umnts		; Fn9=1
-
-### Check functions
-
-Fnsum=$((Fn1 + Fn2 + Fn3 + Fn4 + Fn5 + Fn6 + Fn7 + Fn8 + Fn9))
-
-	echo " Fnsum: ${Fnsum}"
-	echo "$Fnsum" >Func
-	echo " Func :" "$(<Func)"
-
-#=====#=====# Set logging #===========#
+#==========# Set logging #==========#
 
 } |& tee inst.log
-
